language: php

php:
 - 5.3
 - 5.4
 - 5.5
 - 5.6
 - hhvm
 - nightly

before_script:
 - composer self-update
 - composer install --prefer-source --no-interaction --dev

script:
 - phpunit --coverage-text

matrix:
 allow_failures:
  - php: hhvm
  - php: nightly